export const colors = {
    white: "#f2f3f4",
    grey: "#d9d9d9",
    starYellow: "#FFD700",
    starBackground: "#1D3141",
    starBackgroundHover: "#1D314199",
    transparentWhite: "rgba(242, 243, 244, 0.9)",
    yellowText: "#ffe8bc",
    titleColor: "#1D3141",
    navbarBackground: "#1D3141",
    heroPrimaryButtonTextColor: "#1D3141",
    heroPrimaryButtonBackground: "#ffe8bc",
    heroPrimaryButtonHover: "#fbca6e",
    heroSecondaryButtonTextColor: "#ffe8bc",
    heroSecondaryButtonBorderWidth: "2px",
    heroSecondaryButtonBorderColor: "#ffe8bc",
    heroSecondaryButtonBorderHover: "#ffa500",
    heroSecondaryButtonBackgroundHover: "#ffa50026",
    heroImageOverlay: "#1D314150",
    reviewsGradient: "linear-gradient(#E3CAAB, #CBA093)",
    primaryButtonTextColor: "#ffe8bc",
    primaryButtonBackground: "#1d3141",
    primaryButtonHover: "#1f4360",
    secondaryButtonTextColor: "#1d3141",
    secondaryButtonBorderWidth: "2px",
    secondaryButtonBorderColor: "#1d3141",
    secondaryButtonBackgroundHover: "#1d314133",
    deleteButtonTextColor: "#da2222",
    deleteButtonBorderColor: "#da2222",
    deleteButtonBackgroundHover: "#ff000033",
}