import type { AllFlatsStrings } from "../types/allFlatsTypes";

export const allFlatsStrings: AllFlatsStrings = {
  emptyLabel: "No se ha agregado ningún elemento",
  searchBar: {
    placeholder: "Buscar",
    icon: "src/assets/searchIcon.webp",
    type: "searchBar",
    id: "searchBar",
  },
  toggleButton: {
    tableIconTooltip: "Modo Tabla",
    tableIconOn: "src/assets/tableIconOn.webp",
    tableIconOff: "src/assets/tableIconOff.webp",
    tableIconAlt: "Tabla",
    gridIconTooltip: "Modo Cuadrícula",
    gridIconOn: "src/assets/gridIconOn.webp",
    gridIconOff: "src/assets/gridIconOff.webp",
    gridIconAlt: "Cuadrícula",
  },
  favoriteButton: {
    tooltip: "Mostrar favoritos",
    favoriteIconOn: "src/assets/star.webp",
    favoriteIconOff: "src/assets/starGrey.webp",
    favoriteIconAlt: "Favoritos",
  },
  filter: {
    iconSrc: "src/assets/filter.webp",
    iconAlt: "Filter",
    label: "Filtros",
    filters: [
      {
        label: "Ciudad",
        type: "select",
        id: "cityFilter",
      },
      {
        label: "Rango de precio",
        type: "slider",
        id: "priceFilter",
        min: 0,
        max: 500,
        step: 10,
        defaultValue: [0, 500],
      },
      {
        label: "Rango de tamaño del área",
        type: "slider",
        id: "areaFilter",
        min: 0,
        max: 500,
        step: 10,
        defaultValue: [0, 500],
      },
    ],
  },
  sort: {
    label: "Orden",
    type: "select",
    id: "sort",
    options: ["Sin Ordenar", "Ciudad", "Precio", "Tamaño del área"],
  },
  labels: {
    city: "Ciudad: ",
    address: "Dirección: ",
    area: "Área: ",
    airConditioning: "Aire acondicionado: ",
    yearBuilt: "Año de construcción: ",
    dateAvailable: "Fecha de disponibilidad: ",
    rentPrice: "Precio: ",
    createdAt: "Creado el: ",
  },
  options: {
    yes: "Si",
    no: "No",
  },
  imgAlt: "Card Image",
  favorite: {
    tooltip: "Agregar a favoritos",
    favoriteIcon: "src/assets/star.webp",
    unfavoriteIcon: "src/assets/starGrey.webp",
    alt: "Agregar a favoritos",
  },
  tableHead: [
    "Nombre",
    "Ciudad",
    "Calle",
    "Número",
    "Área",
    "A/C",
    "Año de construcción",
    "Fecha de disponibilidad",
    "Creado",
    "Precio de renta",
    "Foto",
    "Favoritos",
  ],
  allFlatsFiltered: [],
  newFlat: "Nueva Publicación",
  searchOn: false,
  filtersOn: {
    cityOn: false,
    priceOn: false,
    areaOn: false,
  },
};
